### PR TITLE
STREAMLINE-596 Use Schema from registry/common module

### PR DESCRIPTION
**Pull request by satishd**

### CODE REVIEW

**Comment by satishd** [comment]
@harshach Pinging for review.

**Comment by HeartSaVioR** [comment]
Just 2 cents: we might want to think about streamline and registry as separate projects.
Schema class is used for more than communicating with registry, like defining schema for storable, which is not relevant to registry. Looks like unneeded coupling.

**Comment by satishd** [comment]
> Just 2 cents: we might want to think about streamline and registry as separate projects.
Schema class is used for more than communicating with registry, like defining schema for storable, which is not relevant to registry. Looks like unneeded coupling.

@HeartSaVioR Actually, it is the other way. Storage is needed by registry also and we want to maintain storage module in registry repo and that module should be used in streamline. It is same with dependent common classes like Schema. There is a task to remove storage module from streamline and use storage module from registry repo.

@harshach You can add more if any.

**Comment by HeartSaVioR** [comment]
Yes there're some more duplicated things between projects. May be better to have common module(s), and ideally common module(s) might be better to move to the another project. 
As I commented, it's just 2 cents, and we could move them out of later whenever necessary.

**Comment by harshach** [comment]
+1

**Pull request merged**
