### PR TITLE
STREAMLINE-782: Need an API to get current user when in secure mode

### PR DESCRIPTION
**Pull request by arunmahadevan**
@shahsank3t , you can test it with "GET api/v1/catalog/users/current" in secure mode.

### CODE REVIEW

**Comment by harshach** [comment]
@shahsank3t why we need this api. We should be able to use the cookie that get stored once auth completes

**Comment by shahsank3t** [comment]
@harshach I believe in the cookie, will only have the user name and not userId. Regards of that, UI still needs to call another API to find that user's role so this API can return all the info in one go, like user information and role information.

**Comment by arunmahadevan** [comment]
@shahsank3t, the proposed api will give you an user id only if the user is registered in the streamline db. For super users that are not registered (only specified as admin user in streamline.yaml) it will return you an "admin" flag indicating if the user is an admin or not. For "admin" users you don't need to check for roles, they will have all access.

**Comment by shahsank3t** [comment]
@arunmahadevan oh, OK. "admin" flag is good.
IMO it would be good if we can also add user & role information in the API if a particular user is registered.

**Comment by harshach** [comment]
@arunmahadevan @shahsank3t +1 on having role info. It will help in showing the right navigation options etc..

**Comment by shahsank3t** [comment]
@arunmahadevan 

API: http://pm-eng1-cluster4.field.hortonworks.com:7777/api/v1/catalog/users/current

Error Response: {"responseMessage":"User 'streamline-hdp/pm-eng1-cluster4.field.hortonworks.com@EXAMPLE.COM' is not in the user database or in the admin principals"}

cc: @harshach

**Comment by arunmahadevan** [comment]
@shahsank3t , i made some fixes and rebased it on top of https://github.com/hortonworks/streamline/pull/564
Can you try again?

**Pull request merged**
