### PR TITLE
STREAMLINE-770 TestSource/TestSink Improvements

### PR DESCRIPTION
**Pull request by HeartSaVioR**
* add 'occurrence' to test source which makes source spout emitting test records multiple times
* implement 'event logging' to topology test run
  * test spouts will log events to the file which are just emitted
  * test bolts will log events to the file which bolts receive
  * all components will log events to the same file (log file is per test run for now)
* add API endpoint to retrieve events for such topology test run
  * /topologies/:topologyId/testhistories/:historyId/events/(:componentName)

Sample output
----

* /api/v1/catalog/topologies/1/testhistories/6/events

```
{"entities":[{"timestamp":1492503551060,"componentName":"KAFKA","streamlineEvent":{"driverId":24,"truckId":97,"eventTime":"00:13.0","eventType":"Normal","longitude":-88.77,"latitude":40.76,"eventKey":"24|97|9223370572464762855","correlationId":"3.66088E+18","driverName":"Don Hilborn","routeId":1090292248,"routeName":"Peoria to Ceder Rapids Route 2","eventDate":"2016-05-27-22","miles":426}},{"timestamp":1492503551060,"componentName":"KAFKA2","streamlineEvent":{"driverId":24,"truckId":97,"eventTime":"00:13.0","eventType":"Normal","longitude":-88.77,"latitude":40.76,"eventKey":"24|97|9223370572464762855","correlationId":"3.66088E+18","driverName":"Don Hilborn","routeId":1090292248,"routeName":"Peoria to Ceder Rapids Route 2","eventDate":"2016-05-27-22","miles":426}}
,...,
{"timestamp":1492503553234,"componentName":"KAFKA-1","streamlineEvent":{"latitude_MAX":40.76,"driverId":24}}]}
```

* /api/v1/catalog/topologies/1/testhistories/6/events/MAX_LATITUDE

```
{"entities":[{"timestamp":1492503553173,"componentName":"MAX_LATITUDE","streamlineEvent":{"driverId":24,"truckId":97,"eventTime":"00:13.0","eventType":"Normal","longitude":-88.77,"latitude":40.76,"eventKey":"24|97|9223370572464762855","correlationId":"3.66088E+18","driverName":"Don Hilborn","routeId":1090292248,"routeName":"Peoria to Ceder Rapids Route 2","eventDate":"2016-05-27-22","miles":426}},{"timestamp":1492503553173,"componentName":"MAX_LATITUDE","streamlineEvent":{"driverId":32,"truckId":42,"eventTime":"00:13.1","eventType":"Normal","longitude":-90.04,"latitude":35.19,"eventKey":"32|42|9223370572464762755","correlationId":"3.66088E+18","driverName":"Ryan Templeton","routeId":1090292248,"routeName":"Peoria to Ceder Rapids Route 2","eventDate":"2016-05-27-22","miles":183}},{"timestamp":1492503553174,"componentName":"MAX_LATITUDE","streamlineEvent":{"driverId":31,"truckId":18,"eventTime":"00:13.1","eventType":"Normal","longitude":-94.35,"latitude":38.33,"eventKey":"31|18|9223370572464762726","correlationId":"3.66088E+18","driverName":"Rommel Garcia","routeId":1594289134,"routeName":"Memphis to Little Rock Route 2","eventDate":"2016-05-27-22","miles":34}},
...,
{"timestamp":1492503553217,"componentName":"MAX_LATITUDE","streamlineEvent":{"driverId":32,"truckId":42,"eventTime":"00:13.1","eventType":"Normal","longitude":-90.04,"latitude":35.19,"eventKey":"32|42|9223370572464762755","correlationId":"3.66088E+18","driverName":"Ryan Templeton","routeId":1090292248,"routeName":"Peoria to Ceder Rapids Route 2","eventDate":"2016-05-27-22","miles":183}},{"timestamp":1492503553218,"componentName":"MAX_LATITUDE","streamlineEvent":{"driverId":31,"truckId":18,"eventTime":"00:13.1","eventType":"Normal","longitude":-94.35,"latitude":38.33,"eventKey":"31|18|9223370572464762726","correlationId":"3.66088E+18","driverName":"Rommel Garcia","routeId":1594289134,"routeName":"Memphis to Little Rock Route 2","eventDate":"2016-05-27-22","miles":34}}]}
```

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
@harshach 
We discussed about retention and decided to let test run overwrite previous event log file. While testing I realized the event log file size is not that huge, so for now I just create event log file per test run (history). 
Please let me know if you think it would be better to have retention or back to overwrite per topology.

Events are presented as it has been written to the file and not explicitly sorted by timestamp. Please let me know if we want to sort explicitly.

@shahsank3t 
Please have a look at output format of events API endpoint.

Thanks all in advance!

**Comment by harshach** [comment]
@shahsank3t this api is for the new mocks that I passed. Please take a look and see if we can adopt this api to build those pages. Please added any changes necessary.

**Comment by shahsank3t** [comment]
@HeartSaVioR Integrated this PR with the UI and overall works good. 
Just one thing, please add an API endpoint to download the eventlogs file. Thanks in advance.

**Comment by HeartSaVioR** [comment]
@shahsank3t Done.
`/api/v1/catalog/topologies/:topologyId/testhistories/:historyId/events/download`

**Comment by shahsank3t** [comment]
@HeartSaVioR While making PUT request call to "api/v1/catalog/topologies/:topologyId/testcases/:testCaseId/sources/:sourceId", we are getting SQLException.

Example API: [PUT] api/v1/catalog/topologies/7/testcases/37/sources/13
Response: {"responseMessage":"An exception with message [com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '37-13' for key 'testcase_source'] was thrown while processing request."}

**Comment by HeartSaVioR** [comment]
@shahsank3t
Which backend are you using? I'm using mysql but can't reproduce the issue. Did you update the table `topology_test_run_case_source` to the last schema?

**Comment by shahsank3t** [comment]
@HeartSaVioR 
I am using mysql and after resetting the db again, strangely PUT worked for me now.

+1 Overall this PR is good with respective to UI integration

**Comment by HeartSaVioR** [comment]
@shahsank3t Great. Thanks for verifying!

**Pull request merged**
