### PR TITLE
STREAMLINE-789: Kafka Metadata should return broker hosts and all the…

### PR DESCRIPTION
**Pull request by hmcl**
… listeners

   - Added broker host and port information grouped by security protocol to the JSON security entry

### CODE REVIEW

**Comment by hmcl** [comment]
@harshach @priyank5485 can you take a look in particular at KafkaBundleHintProviderTest.java and KafkaBundleHintProvider.java to make sure the hint info is being added properly. 

Currently the KafkaMetadataResource rest calls have the following output (i.e. protocol info is only added to the brokers json, but not to topics).
`
{
  "brokers": [
    {
      "host": "pm-eng1-cluster2.field.hortonworks.com",
      "port": 6667
    },
    {
      "host": "pm-eng1-cluster3.field.hortonworks.com",
      "port": 6667
    },
    {
      "host": "pm-eng1-cluster4.field.hortonworks.com",
      "port": 6667
    }
  ],
  "security": {
    "authentication": {
      "enabled": true,
      "scheme": "kerberos"
    },
    "authorizer": {
      "invoked": false,
      "msg": "Authorization not enforced. Every authenticated user has access to all metadata info"
    }
  },
  "protocol": {
    "SASL_PLAINTEXT": [
      "pm-eng1-cluster2.field.hortonworks.com:6667",
      "pm-eng1-cluster3.field.hortonworks.com:6667",
      "pm-eng1-cluster4.field.hortonworks.com:6667"
    ]
  }
}
`

`
{
  "topics": [
    "truck_test",
    "ambari_kafka_service_check",
    "truck_events",
    "truck_events_stream",
    "test",
    "__consumer_offsets"
  ],
  "security": {
    "authentication": {
      "enabled": true,
      "scheme": "kerberos"
    },
    "authorizer": {
      "invoked": false,
      "msg": "Authorization not enforced. Every authenticated user has access to all metadata info"
    }
  }
}

`

**Comment by priyank5485** [comment]
@hmcl There are two hint provider classes KafkaSinkBundleHintProvider and KafkaBundleHintProvider for sink and source respectively. We need to handle bot source and sinks. Also, if I understand it correctly the way hints are returned is that per cluster its a json object. Each json object has a key which is the ui field name in the json spec for that component and then suggestions of values for that field name. After the latest change to switch to storm-kafka-client we have some new fields like bootstrapServers,  serviceName, etc. I was expecting to see the hint response to have keys for those fields and values as suggestions. Am i missing anything?

**Comment by priyank5485** [comment]
@hmcl Just had a call with @shahsank3t Can we have the hint response for kafka source and sink have the following fields 
``` json
{
  "1": {
    "cluster": {
      "id": 1,
      "name": "clusterA",
      "ambariImportUrl": "http://172.22.125.40:8080/api/v1/clusters/clusterA",
      "description": "This is an auto generated description",
      "timestamp": 1495174176866
    },
    "hints": {
      "bootstrapServers": {
        "PLAINTEXT":
          "gk-sl-17jan-1.openstacklocal:6667"
      },
      "topic": [
        "ambari_kafka_service_check",
        "truck_events_stream"
      ],
      "securityProtocol": ["PLAINTEXT"],
      "kafkaServiceName": "kafka"
    }
  }
}
```

**Comment by hmcl** [comment]
The changes in this PR were included as part of PR https://github.com/hortonworks/streamline/pull/590

**Pull request closed without merging**
