### PR TITLE
ISSUE-1277 exclude slf4j-log4j12 dependency

### PR DESCRIPTION
**Pull request by ghajos**

### CODE REVIEW

**Comment by ghajos** [comment]
@arunmahadevan Can you please take a look at?

**Comment by arunmahadevan** [comment]
@ghajos , the changes looks good. But is it an issue only with 3.1-maint branch ? Recently there has been no changes to this branch. 

How about the master branch ?

**Comment by ghajos** [comment]
@arunmahadevan Probably the dependency is arrived with the new builds of HDF stack and independent of Streamline's code as it occurs only when source patch is applied. Checked it on master/HDF-3.2.0.0 and it is not an issue there.

**Comment by ghajos** [comment]
@arunmahadevan The problem occurs after applying the source patch. Please update the dependencies to those HDF-3.1-maint has
`$ wget http://s3.amazonaws.com/dev.hortonworks.com/HDF/centos7/3.x/PATCH_FILES/3.1.1.0-56/patch_files/streamline-source.patch`
`$ git apply streamline-source.patch`
`$ mvn clean install`

**Comment by ghajos** [comment]
@arunmahadevan Thank you!

**Pull request merged**
