### PR TITLE
ISSUE-996 Removed findbugs-annotation 1.3.2 module dependency as it h…

### PR DESCRIPTION
**Pull request by satishd**
…as LGPL license.

### CODE REVIEW

**Comment by arunmahadevan** [comment]
+1. Is it required only for build or gets packaged in the binaries?

**Comment by satishd** [comment]
@arunmahadevan It is packaged with binaries like all other dependencies.

**Comment by arunmahadevan** [comment]
@satishd thanks, merged to HDF-3.0-maint. Can you raise a PR for master as well?

**Comment by satishd** [comment]
@arunmahadevan Raised #998 for master branch.

**Pull request merged**
