### PR TITLE
ISSUE-763 Support transactions for streamline

### PR DESCRIPTION
**Pull request by raju-saravanan**
ISSUE-763 Support transactions for streamline

### CODE REVIEW

**Comment by arunmahadevan** [comment]
@raju-saravanan there seems to be some travis failures, can you take a look?. Once the changes are ready to be reviewed let us know.

**Comment by arunmahadevan** [comment]
@HeartSaVioR , can you help review once the changes are complete?

**Comment by HeartSaVioR** [comment]
@arunmahadevan Sorry forgot this. I'll review this today.

**Comment by HeartSaVioR** [comment]
@raju-saravanan 
Build in Travis CI indicates that there're compile error on the patch. Could you have a look?
Also please resolve conflict.

Btw, I guess we need to add `@UnitOfWork` to enable transaction for specific method, and the patch doesn't add the annotation so there's no functional change. May need to file another issue to address it as well.

**Comment by satishd** [comment]
This PR needs to be updated with recent changes done in registry's common storage transaction api with https://github.com/hortonworks/registry/pull/286.

**Comment by raju-saravanan** [comment]
@HeartSaVioR : Sorry to mislead, but this branch doesn't have all the changes that is required for transaction support. I will update this branch in a day or two, then you can review the changes.

**Comment by HeartSaVioR** [comment]
@raju-saravanan OK. Please change PR's title to add "WIP", and remove it after finishing your work.

**Comment by raju-saravanan** [comment]
@arunmahadevan and @HeartSaVioR  can you guys review this PR? I have tested it against MySQL, Postgres and Oracle.

**Comment by HeartSaVioR** [comment]
This patch looks like preparation of applying transaction and I could see few place adding this. Could we file an issue for applying transaction to all the places? Maybe some other folk which is more familiar with Streamline could take up the issue.

**Comment by raju-saravanan** [comment]
@HeartSaVioR: This patch blindly applies a transaction to all the resource methods. Changes in this patch are first cut for supporting transactions, once its merged I was hoping that one of you guys can dig into the APIs and see which resource method requires transaction and which don't and use UnitOfWork annotation to apply/don't apply a transaction to that resource method.

**Pull request closed without merging**
