### PR TITLE
ISSUE-1046: Allow user to select nested fields in Druid Sink UI

### PR DESCRIPTION
**Pull request by satishwaghela**

### CODE REVIEW

**Comment by shahsank3t** [comment]
@omkreddy could you test this PR and verify if it's all good?

**Comment by satishwaghela** [comment]
dimensionsnestedfields
The screenshot shows the format of passing fields with stream id as a prefix.

**Comment by omkreddy** [comment]
@satishwaghela 

looks like  "select all"  output is also including  "stream Id" string. we need to exclude the string from the output.

"dimensions": [
  **"kafka_stream_1",**
  "kafka_stream_1:user_id",
  "kafka_stream_1:text",
  "kafka_stream_1:review_id",
  "kafka_stream_1:stars",
  "kafka_stream_1:date",
  "kafka_stream_1:business_id",
  "kafka_stream_1:type",
  "kafka_stream_1:votes.funny",
  "kafka_stream_1:votes.useful",
  "kafka_stream_1:votes.cool"
]

**Comment by satishwaghela** [comment]
@omkreddy 
I have fixed stream id was getting included in "Select All"

**Comment by arunmahadevan** [comment]
@omkreddy , can you review and comment if this patch can be merged ?

**Comment by omkreddy** [comment]
LGTM. done sanity test. can be merged after rebasing the PR

**Comment by arunmahadevan** [comment]
@satishwaghela can you rebase ?

**Comment by satishwaghela** [comment]
@arunmahadevan , I have rebased and resolved conflict.

**Comment by arunmahadevan** [comment]
Thanks @satishwaghela merged to master

**Pull request closed without merging**
