### PR TITLE
ISSUE-1107: UI issues in view mode

### PR DESCRIPTION
**Pull request by sameer79**
@arunmahadevan @HeartSaVioR @shahsank3t please review and comment.

### CODE REVIEW

**Comment by arunmahadevan** [comment]
@sameer79 , the reported issues have been addressed. A couple more that will be good to fix.

1. In the Sampling screen selected "Event Id" and "Root Id". Able the view the values. However after I go back to view mode and come back to the sampling view, these settings are not saved. Same behavior while selecting "host" in the log search. Can we save these settings?

2. The samples are always displayed in the ascending order so to view the latest event, one needs to select "last 5 mins" and then navigate till the last event. I will be good to add an option to reverse sort. @HeartSaVioR does solr support this ? If so we can provide an extra "sort" order in the API and UI can use it.

**Comment by HeartSaVioR** [comment]
@arunmahadevan @sameer79 
Please refer the parameters in PR's body: https://github.com/hortonworks/streamline/pull/1096
For events we have sort option, for log we don't have the sort option, but I can add it if we want.

**Comment by arunmahadevan** [comment]
@HeartSaVioR , thanks for the info. It will be good to add for logs as well. but we can track that as a separate issue.

@sameer79 , so can you address the below ?
1. In the Sampling screen selected "Event Id" and "Root Id". Able the view the values. However after I go back to view mode and come back to the sampling view, these settings are not saved. Same behavior while selecting "host" in the log search. Can we save these settings?

2. Add a sort option in the UI to view the result in ascending or descending order.

**Comment by shahsank3t** [comment]
@arunmahadevan @HeartSaVioR 
I'll be addressing these UI changes since @sameer79 is on vacation. I'll create another PR with this PR commit and my changes above that in short time and close this one.

**Comment by shahsank3t** [comment]
Raised PR https://github.com/hortonworks/streamline/pull/1114 with @sameer79's changes and addressed the comments above. Closing this now.

**Pull request closed without merging**
