### PR TITLE
ISSUE-1054: UI changes in topology view mode for component metrics and log level

### PR DESCRIPTION
**Pull request by joylyn**
Fix for #1054.
Adds UI side changes for #1023 and #1014 .
This PR does not include UI support for sampling, it will be provided in separate PR which is a WIP.

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
I pulled all the pending PRs related to this and built & tested.
Below link is the working branch:
https://github.com/HeartSaVioR/streamline/tree/ISSUE-1054-pulling-also-1001-1033-1014-1023

Please note that I've resolved some conflicts and build failures. I'd like to see other PRs sequentially get reviewed merged sooner.

**Comment by HeartSaVioR** [comment]
The UI looks like working properly with Chrome, but not Safari and Firefox.
Please take a look at component box from both Overview tab and Metrics tab.

> Overview

>> Chrome

screen shot 2017-12-04 at 1 37 04 pm

>> Firefox & Safari (same issue)

screen shot 2017-12-04 at 1 36 58 pm

> Metrics

>> Chrome

screen shot 2017-12-04 at 1 35 15 pm

>> Firefox & Safari (same issue)

screen shot 2017-12-04 at 1 35 08 pm

I also tested dynamic log level and it worked well.

**Comment by joylyn** [comment]
The Firefox and Safari issue has been fixed.

**Comment by HeartSaVioR** [comment]
@joylyn Sorry, but could you follow up the change of API endpoints? 

While reviewing PR #1023, we decided to append `/metrics` to the postfix of topology catalog API endpoint instead of having new root path `/api/v1/viewmode/`.

  * /api/v1/catalog/topologies/:topologyId/metrics
  * /api/v1/catalog/topologies/:topologyId/sources/metrics
  * /api/v1/catalog/topologies/:topologyId/sources/:sourceId/metrics
  * /api/v1/catalog/topologies/:topologyId/processors/metrics
  * /api/v1/catalog/topologies/:topologyId/processors/:processorId/metrics
  * /api/v1/catalog/topologies/:topologyId/sinks/metrics
  * /api/v1/catalog/topologies/:topologyId/sinks/:sinkId/metrics

Thanks in advance!

**Comment by joylyn** [comment]
@HeartSaVioR I have made the change for the new APIs.

**Comment by HeartSaVioR** [comment]
I'm updating the cluster with changes on #1023 and #1055 (this). Will let you know once I complete.

**Comment by HeartSaVioR** [comment]
FYI: updated the cluster.

**Comment by HeartSaVioR** [comment]
I had a short talk with @joylyn regarding the rule to decide unit of latency:

* less than 1000 (1 sec): represent the value as millisecond
* equal or more than 1000 (1 sec): represent the value as second

@shahsank3t @arunmahadevan @joylyn 
Please chime in if you have better rule for representing. Thanks!

**Comment by shahsank3t** [comment]
@HeartSaVioR @joylyn 
I believe that's the best way to show the units.
For latency, yes keep ms till value is under 1000 and then show 1 sec until it reaches to minutes & hours.
For others, show plain numbers until it reaches to thousand and then start with k(for thousand), m(for millions), b(for billions) and t(for trillions) hoping it would be rare case to go beyond that ;)

Above has already been implemented and I think we should keep as is unless we have consensus to change it.

**Comment by arunmahadevan** [comment]
+1

@shahsank3t , @joylyn , thanks for the patch. I have done some basic testing and things seems to work well. @HeartSaVioR  may make some changes to address https://github.com/hortonworks/streamline/pull/1032#pullrequestreview-81374655.

After that we can retest this and merge.

**Comment by arunmahadevan** [comment]
A few minor UI issues.

1. On clicking the show metrics "All components" to change the component, theres a blank entry at the bottom.

2. On selecting a component here, the "Sampling percentage" box is automatically displayed in the graph. This is not required.

3. On selecting a subsection of the chart (say input/output), nothing happens. Is something missing?

**Comment by HeartSaVioR** [comment]
@joylyn 
From #1032 we've allowed metrics from previous to be "null" if there're not enough metric points to be evaluated. (for example, 10 mins time range when topology uptime 15 mins, which current time bucket is for 10 mins but prev time bucket is only for 5 mins) 

If UI encounters null from `prev*`, don't represent trending (+ or -).

**Comment by shahsank3t** [comment]
> On selecting a subsection of the chart (say input/output), nothing happens. Is something missing?

@arunmahadevan Yes we missed on adding a functionality. Basically, if the user selects a subsection, we will update the start/end time for everything and proper show values. Later if the user wants to go back to normal state, they can use date-time range picker on the UI and select timeframe they want to see.

**Comment by joylyn** [comment]
@HeartSaVioR  @arunmahadevan I have made the requested changes.
Please note that since sampling is not yet enabled, the respective buttons is not seen for now.

**Comment by arunmahadevan** [comment]
The earlier comments have been addressed. A few other observations:

1. After selecting a component, no easy way to "de-select" the component and view the metrics for all. I figured out a way by selecting "All components" from the bottom, but its not intuitive. Maybe on clicking an already selected component, we should de-select it.

2. After selecting a sub-section of the chart , how do I go back to full view ?

**Comment by shahsank3t** [comment]
>1. After selecting a component, no easy way to "de-select" the component and view the metrics for all. I figured out a way by selecting "All components" from the bottom, but it's not intuitive. Maybe on clicking an already selected component, we should de-select it.

Yeah, we will add de-select component by clicking already selected component.

>2. After selecting a sub-section of the chart, how do I go back to full view?

You can click on date picker at the top (besides log search icon) and select the timeframe. That's the same time frame that gets changes when you select a sub-section in the chart.

cc: @arunmahadevan  @joylyn

**Comment by shahsank3t** [comment]
@joylyn also look at the changes @arunmahadevan  mentioned here: https://github.com/hortonworks/streamline/pull/1037#pullrequestreview-82040858

**Comment by joylyn** [comment]
@arunmahadevan  @shahsank3t 
 - The "selection/de-selection" of component on clicking is already implemented.
 - I have fixed the issue mentioned in #1037 (review)

**Comment by joylyn** [comment]
merged conflicts and rebased.

**Comment by arunmahadevan** [comment]
After selecting a log level and percentage, if I refresh the screen the setting disappears. Is this already addressed in this PR ?

**Comment by arunmahadevan** [comment]
+1

**Pull request closed without merging**
