### PR TITLE
ISSUE-1090 Provide backend API endpoint for fetching events indexed in Log Search service

### PR DESCRIPTION
**Pull request by HeartSaVioR**
* introduce new API endpoint: /topologies/:topologyId/events
  * mandatory params
    * topologyId
    * from
    * to
  * optional params
    * componentName
    * searchString
    * searchEventId
    * start
    * limit
    * ascending (true/false)
  * please refer to parameters in "/topologies/:topologyId/logs" (#1002)

`searchString` is applied to keyValues, headers, auxKeyValues (OR query).
`searchEventId` is applied to eventId, rootIds, parentIds (OR query).

This closes #1096

### CODE REVIEW

**Comment by shahsank3t** [comment]
@HeartSaVioR was just wondering if we need to have Ambari_Infra added to the environment of the topology to get the response for this API or will work without as well, unlike log search?

**Comment by HeartSaVioR** [comment]
@shahsank3t This leverages Ambari Infra as same as log search. I'm also requesting for review on storm log config for ingesting events log file and publish to Ambari Infra.

**Comment by shahsank3t** [comment]
@HeartSaVioR build is failing (check travis-ci logs) on my local too, can you please check.

**Comment by HeartSaVioR** [comment]
@shahsank3t My bad. Just fixed.

**Comment by arunmahadevan** [comment]
@HeartSaVioR , I triggered another travis build; it seemed to have failed in registry-webservice.

**Comment by HeartSaVioR** [comment]
Same issue is filed in Travis CI repo.
https://github.com/travis-ci/travis-ci/issues/8940

**Comment by arunmahadevan** [comment]
+1, Will merge it after my local build passes.

@shahsank3t , raised an issue for the relevant UI changes - https://github.com/hortonworks/streamline/issues/1097

**Comment by arunmahadevan** [comment]
Thanks @HeartSaVioR , merged to master

**Pull request closed without merging**
