### PR TITLE
STREAMLINE-733: Metadata API for TopologyEditor component bar

### PR DESCRIPTION
**Pull request by arunmahadevan**
Right now it stores with a dummy user id, changes needs to be made once https://github.com/hortonworks/streamline/pull/521 is merged to populate the actual user id.

### CODE REVIEW

**Comment by harshach** [comment]
@arunmahadevan we also need to handle this in non-secure version. In non-secure cluster the changes to the toolbar will be system-wide. Do we handle this case?

**Comment by arunmahadevan** [comment]
@harshach in non-secure mode we map it with a dummy user id and the changes will be system wide. I will make changes to this PR to handle the secure/non-secure modes now that the authorization patch is merged.

**Comment by arunmahadevan** [comment]
@harshach made changes to handle authorization and mapping it to anonymous user in non-secure mode and real user in secure mode.

**Comment by harshach** [comment]
Thanks @arunmahadevan . +1.

**Pull request merged**
