### PR TITLE
ISSUE-1105 Fix log level status API to respond status 200 when topology is not running

### PR DESCRIPTION
**Pull request by HeartSaVioR**
* change response format to be similar with sampling status API

Response format of `/logconfig` (both GET/POST) will contain:
- success (always presented)
- enabled (only when success = true)
- logLevel (only when enabled = true)
- epoch (only when enabled = true)

This format is similar to sampling status API.

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
@arunmahadevan @shahsank3t @sameer79
Please take a look. Given that this patch modifies the API endpoint paths which are related to #1101, this patch is effectively blocker for #1101.

@sameer79 I'm sorry, but I think this patch should be also applied to #1101. Please take a look at the API endpoint paths.

**Comment by HeartSaVioR** [comment]
@shahsank3t 
> componentName as null

That's valid message: component is determined by thread name, and there're many background threads which also writes valuable log messages. Sometimes it's more helpful than executor thread.

@arunmahadevan 
If we want to hide log messages from non-executor threads plesae let me know.

**Comment by arunmahadevan** [comment]
@HeartSaVioR , lets keep logs from all threads. The user can filter based on component name to see executor thread logs.

**Comment by arunmahadevan** [comment]
+1

**Comment by HeartSaVioR** [comment]
@arunmahadevan Rebased. Once I have +1 I'll just merge to avoid rebasing again.

**Pull request closed without merging**
