### PR TITLE
ISSUE-597: Kafka component bundle changes for UI when running in secu…

### PR DESCRIPTION
**Pull request by priyank5485**
…red mode

Change-Id: I18b288291538012fc749417b41459a0b297e7255

### CODE REVIEW

**Comment by priyank5485** [comment]
@shahsank3t I have added _required to the hint for security related fields. For SASL(prefix is security_kerberos) _required are mandatory fields. For SSL(prefix is security_ssl) _required are mandatory fields. I have also made securityProtocol a mandatory field. Let me know if you need any more changes. If not and if they look good you can merge them in to master or let me know and I will merge.

**Comment by shahsank3t** [comment]
+1 looks good.
@priyank5485 you can merge this in.

**Comment by satishd** [comment]
+1, squashed and merged the commits.

**Comment by satishd** [comment]
@shahsank3t merged into master, you can pull latest master and get these changes.

**Comment by satishd** [comment]
@priyank5485 Sorry to push the merged commits into repo master instead of your repo/branch. You can close this PR.

**Comment by HeartSaVioR** [comment]
@satishd FYI: You can add `Closes #NUM` to a squashed commit to close relevant issue/PR.

**Comment by priyank5485** [comment]
@satishd No worries. Closing this now.

**Pull request closed without merging**
