### PR TITLE
ISSUE-968 Join processor output when both streams have same field

### PR DESCRIPTION
**Pull request by sameer79**
Join processor support for multiple streams with same fields name by using a unique alias.
the screenshot below:

joinscreenshot

Stream legends are used to denote which field belong to which stream.
We can have in the way it’s shown in the screenshot or add an icon beside the “Output Fields*” label where a user can hover and check.
I am preferring the former approach so the user doesn’t have to hover over the icon every now and then to verify as it will always be available on the screen.

Open for a suggestion from others.

@shahsank3t  @arunmahadevan  @roshannaik please review and comment.
Thanks in advanced

### CODE REVIEW

**Comment by roshannaik** [comment]
I like the way the duplicate alias reporting is done and also the stream numbering technique .. though it took me a little time to understand how the stream numbers/legend were employed.

Few things I noticed:
Need to relocate the 'Select All' link for the output fields selection box to its bottom right or much closer to it. Given its current proximity to the 'slide interval', it does not give the impression that it is actually related to the output field selector box.
No error indication if 'timestamp field' is not filled and you click OK.
Need better tooltips for:
+ **Timestamp field** : "Field (of type long) indicating the event's time'
+ **Lag ms** : "Max time to wait after window close, for a late arriving event to be part of its window" @arunmahadevan  could please you review this tooltip hint.
What's the way to reorder the output fields easily ?

**Comment by sameer79** [comment]
@roshannaik
Addressed the comment and updated the PR as well.

@shahsank3t  please review.

**Comment by arunmahadevan** [comment]
- Timestamp : "A 'long' field in the event that represents the event-timestamp in milliseconds (epoch-time)'
- Lag ms : "Maximum lag of the event timestamp in milliseconds up to which a late arriving event is included in the current window"

I am not sure what you mean by output stream legends, I think you mean aliases for input streams similar to table alias in SQL join.

"Input stream aliases"
  - window_transform_stream_16 -> window1 (user provided value)
  - window_transform_stream_16 -> window2 (user provided value)

then in the select box,

window1.field1 as f1 
window2.field1 as f2

and so on. If you want to auto-generate aliases that may also be fine, but user may not be able to quickly identify which is 1, 2 and so on.

Also in the generated event I assume it will be referred as "f1" and "f2". You may also need to validate that two fields don't end up having the same alias.

Are these mandatory? By default we could assume input_stream_name.field_name and let user specify aliases only if they want.

**Comment by roshannaik** [comment]
@arunmahadevan , it would be helpful to clarify the word 'lag' here. Basically brief wording to indicate ... starting from when is the lag time calculated.

**Comment by arunmahadevan** [comment]
Lag ms : "Maximum lag of the event timestamp (beyond the window end time) in milliseconds for including a late arriving event in the current window"

is this better?

**Comment by arunmahadevan** [comment]
@shahsank3t , if the field names are unique across streams do you still want to show aliases for them?. May be just display the white box with the field name `[field_name]`. If the user goes and edits the value display `[1 field_name as (alias)]`. 

For duplicate fields, the proposed UI and forcing the user to remove the conflict looks great.

Assume the legends would be displayed at the bottom all the time. This should be renamed to "Input stream legends" or just "Legends: 1 -> foo, 2 -> bar" should be sufficient.

**Comment by roshannaik** [comment]
@arunmahadevan We should allow aliases even if there is no duplication. Users should be able to rename the output fields as they please. Can be quite useful in many cases like when dealing with nested fields.

More refinement to the wording for Lag Ms. See if it looks ok...

**Lag Ms** :  If (time of window close + Lag)  <= timestamp of a late arriving event for same window, the event will be considered for processing.

**Comment by arunmahadevan** [comment]
>We should allow aliases even if there is no duplication. Users should be able to rename the output fields as they please.

Yes by default display the unique "fieldname" and if the user clicks and renames it display the "fieldname as alias". Like the SQL select query where its not mandatory to have alias if the field names are unique.

**Comment by arunmahadevan** [comment]
LagMs, "event time" should be less than "window close + lag" not other way.. I think if we can put it in words rather than less/greater than it would be easier to understand. Lets choose one and go with it..

**Comment by roshannaik** [comment]
Sorry, I meant >=.  Understanding this lag is a bit tricky for new folks due to the mix of wall clock time and timestamps going into it, so whatever we can do to help convey it succinctly would be nice.  Here it is in a more verbal style ...

**Lag Ms** : If timestamp of a late arriving event is less than the wall clock time at which its window closed + Lag, the event will still be considered for processing in that window.

**Comment by arunmahadevan** [comment]
its not the wall clock time, event time.
"If the timestamp of a late arriving event is not "lag" milliseconds beyond the window end time (based on event time), the event will still be considered for processing in that window."

**Comment by sameer79** [comment]
Address comment: https://github.com/hortonworks/streamline/issues/973#issuecomment-341848438

Change in Timestamp fields dropdown
i] mandatary to select one field for per input stream.

and updated PR @arunmahadevan @roshannaik @shahsank3t  please review and comment.

**Comment by roshannaik** [comment]
@shahsank3t 
- need to add validation that window interval and slide interval are > 0
- change caption 'WINDOW INTERVAL TYPE' to 'WINDOW TYPE'

**Comment by sameer79** [comment]
@roshannaik address comment and updated PR as well.

@shahsank3t squash the commit and ready for review and comment.

**Comment by sameer79** [comment]
@roshannaik  Address comment https://github.com/hortonworks/streamline/pull/1004#issuecomment-346198546

@shahsank3t updated PR please review and comment.

**Comment by arunmahadevan** [comment]
@roshannaik, can you comment if the issue you had observed has been addressed now ?

**Comment by roshannaik** [comment]
UI changes look ok... doing some more testing.

**Comment by roshannaik** [comment]
@sameer79 . One more thing. Looks like the same validation from Sliding Interval field has also been accidentally applied to Lag Milliseconds field as well (along with the same error msg).  Lag Ms should allow values >=0.  unlike the Sliding Interval which cannot have 0.

**Comment by sameer79** [comment]
@roshannaik Addressed the comment and updated PR as well.

**Comment by roshannaik** [comment]
latest change has broken the 'timestamp fields' 
screen shot 2017-11-29 at 6 59 29 am

**Comment by roshannaik** [comment]
Tested successfully. Backend looks good. Rebased.
Minor issue in UI needs fix.

**Comment by sameer79** [comment]
@roshannaik  'timestamp fields' issue is fixed. please verify it, Thanks in advance.

**Comment by roshannaik** [comment]
+1  
UI has turned out pretty nice. thanks !

**Pull request closed without merging**
