### PR TITLE
ISSUE-1108 View mode metrics changes

### PR DESCRIPTION
**Pull request by shahsank3t**
1. Removed "Process Time" and renamed "Latency" to "Overall Latency" in the bottom panel for the source.
2. Added "Execute Time" graph for processors and sinks in the bottom panel metrics.

### CODE REVIEW

**Comment by arunmahadevan** [comment]
@shahsank3t the changes looks good. We just need to finalize the labels. I think we can stick to the names in the Storm UI for the sources.

1. In the source (DAG) - Complete latency
2. In the source (bottom panel) - Complete latency
3. In the processors/sinks (DAG) - Process time , Execute time
4. In the processors/sinks (bottom panel) - Process time , Execute time

@HeartSaVioR let me know what you think. For 3, 4 do you think storm's naming ("process latency" and "execute latency") is better ?

@shahsank3t Can you rename the labels for 1 and 2 ? I think you are waiting for backend changes for 3 ? If so lets wait and address 3  in the patch before merging it. 

I have this patch (plus changes in #1107) deployed here - http://ctr-e136-1513029738776-15460-01-000002:7777/

**Comment by shahsank3t** [comment]
@arunmahadevan When showing topology level metrics count (in the bottom panel), for `latency`, should we keep it as is or will it be `Complete Latency` or `Process Time`?

**Comment by arunmahadevan** [comment]
@shahsank3t , I think we need to explicitly mention "Complete latency" only for source. We can show it in the source, bottom bar (with up/down arrows) and also when the bottom panel is expanded (for sources).

For topology level, its kind of implicit that this is a topology level value, so we can just show "Latency" when all components are selected, both in the bottom bar and in the expanded bottom panel.

**Comment by HeartSaVioR** [comment]
@arunmahadevan If we want to make Storm users more familiar with our labels, I'd rather making labels in sync with Storm. If we still want to open a chance with having another streaming engines (though I don't think that's possible becase it will require dropping so many features) I'd rather not. 
I think either is fine even for another streaming engines.

**Comment by arunmahadevan** [comment]
@shahsank3t , can you rename the labels to make it in sync with Storm ?

1. In the source (DAG) - Complete latency
2. In the source (bottom panel) - Complete latency
3. In the processors/sinks (DAG) - Process latency , Execute latency
4. In the processors/sinks (bottom panel) - Process latency, Execute latency
5. All Components - Latency

**Comment by shahsank3t** [comment]
@arunmahadevan @HeartSaVioR 
Renamed the fields and updated the PR.

**Comment by arunmahadevan** [comment]
+1

**Pull request closed without merging**
