### PR TITLE
ISSUE-973: Realtime join processor UI bugs

### PR DESCRIPTION
**Pull request by satishwaghela**

### CODE REVIEW

**Comment by satishwaghela** [comment]
@shahsank3t 
I have addressed your comments. please verify

**Comment by arunmahadevan** [comment]
@satishwaghela , can you rebase?
@roshannaik , can you check if this patch is good to merge?

**Comment by satishwaghela** [comment]
@arunmahadevan, I have rebased this branch with master

**Comment by roshannaik** [comment]
- Can you please change the 'Window Interval Type' to 'Window Size Type'
- In view mode the alignment needs fixing.
join screen shot

**Comment by satishwaghela** [comment]
@roshannaik , I addressed your comments. please verify

**Comment by roshannaik** [comment]
Looks good   +1

**Pull request closed without merging**
