### PR TITLE
STREAMLINE-715: Metadata service should work with secure services (Ready to MERGE)

### PR DESCRIPTION
**Pull request by hmcl**
- Set doAsUser query param for Storm UI from Security Context
  - StormMetadataServiceTest
  - Services execution using Subject.doAs
  - Pass Subject onto ServiceMetadataResources
  - HBaseMetadataService - UserGroupInformation.setConfiguration(config);
  - HBaseMetadataResource, HBaseMetadataService with Subject.doAs(...)

### CODE REVIEW

**Comment by hmcl** [comment]
This patch is still WIP. Namely, I am still testing several scenarios to confirm all is OK. Once I have done more extensive testing I will remove the WIP tag.

I believe that this change also addresses STREAMLINE-742. I am still testing to see if it handles all the cases.

**Comment by hmcl** [comment]
Currently, and temporarily, some code has an `isSecure` flag set to true because the `SecurityContext#isSecure()` is not currently returning true without the authorizer.  It will be removed and is used only to be able to test the code.

This patch is also currently using the streamline subject in order to authenticate and test the authentication code. It will change and instantiate the appropriate subjects as I test the authorization part for the relevant services

**Comment by hmcl** [comment]
@harshach this patch is now ready to merge

**Comment by harshach** [comment]
@hmcl merged into master. please check & close the pr.

**Pull request closed without merging**
