### PR TITLE
ISSUE-1026 Group test mode events in the bottom nav bar

### PR DESCRIPTION
**Pull request by sameer79**
UI-Changes for group event on the bottom nav bar in test mode.
Screenshot below : 

groupeventlog

@arunmahadevan  @shahsank3t  please review and comment.

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
In #1028, a root event can be included to multiple groups, so the representation `start-end` is not correct. Discussed with @arunmahadevan, we can apply same paging (say 1, 2, 3, ...) to nav bar, not representing them as explicitly grouped.

@arunmahadevan Could you recheck this?

**Comment by HeartSaVioR** [comment]
@arunmahadevan 
Since we're now grouping events via comparing all correlated events, the new concept conflicts dynamically updating DAG: groups can be changed while pulling the change. (Even in same group there could be difference for all correlated events while processing the events.)
Do we want to leave this as it is, or let UI wait for backend to be finished (rolling back to before)?

**Comment by arunmahadevan** [comment]
@HeartSaVioR @sameer79, I think we should show the group ids in the bottom panel. There can be multiple overlapping events. E.g. event1 can be part of group1 and group2. So we may just want to show 1, 2, 3 ... in the bottom panel. The should be able see the source events (test case events) in that group from the sources right?

**Comment by HeartSaVioR** [comment]
@arunmahadevan Yes, exactly.

**Comment by arunmahadevan** [comment]
@sameer79 , can you make the changes to display 1, 2, 3..? each number indicating a group.
After that we can merge it.

**Comment by HeartSaVioR** [comment]
@arunmahadevan And showing multiple events too.

**Comment by sameer79** [comment]
@arunmahadevan Just for a double check, Do we need to remove the source-highlight feature too?.

**Comment by arunmahadevan** [comment]
@sameer79 , yes we can remove the source highlighting since we will be displaying the groups now.

**Comment by sameer79** [comment]
@arunmahadevan @HeartSaVioR  Addressed the comment and updated PR as well.

@shahsank3t  please review and comment.

**Comment by arunmahadevan** [comment]
@HeartSaVioR , can you also check and approve the changes?

**Comment by HeartSaVioR** [comment]
OK got it why I'm only one to request. It doesn't show navigation in FF Quantum and also Safari.

> FF Quantum

screen shot 2017-11-28 at 8 28 57 am

> Chrome 62.0.3202.94

screen shot 2017-11-28 at 8 36 42 am

> Safari 

screen shot 2017-11-28 at 8 40 32 am

Looks like event representation in FF and Safari is also odd.

@arunmahadevan @shahsank3t Do we have any browser compatibility notice? If we are only supporting Chrome I can change my vote back to +1, but if not, it should be fixed.

**Comment by HeartSaVioR** [comment]
[Streaming-Analytics-Trucking-Ref-App(1).json.txt](https://github.com/hortonworks/streamline/files/1508013/Streaming-Analytics-Trucking-Ref-App.1.json.txt)

Please remove postfix '.txt' to be imported.

Please create test case with records information below:

> Test-SpeedStream
```
[
  {
    "eventTime": "2017-09-26 14:54:45.163",
    "eventSource": "truck_speed_event",
    "truckId": 23,
    "driverId": 13,
    "driverName": "Suresh Srinivas",
    "routeId": 4,
    "route": "Des Moines to Chicago",
    "speed": 83
  },
  {
    "eventTime": "2017-09-26 14:54:52.099",
    "eventSource": "truck_speed_event",
    "truckId": 23,
    "driverId": 13,
    "driverName": "Suresh Srinivas",
    "routeId": 4,
    "route": "Des Moines to Chicago",
    "speed": 96
  }
]
```

> Test-GeoStream

```
[
  {
    "eventTime": "2017-09-26 14:54:44.451",
    "eventSource": "truck_geo_event",
    "truckId": 23,
    "driverId": 13,
    "driverName": "Suresh Srinivas",
    "routeId": 4,
    "route": "Des Moines to Chicago",
    "eventType": "Overspeed",
    "latitude": 41.62,
    "longitude": -93.58,
    "correlationId": 1,
    "geoAddress": ""
  },
  {
    "eventTime": "2017-09-26 14:54:50.451",
    "eventSource": "truck_geo_event",
    "truckId": 23,
    "driverId": 13,
    "driverName": "Suresh Srinivas",
    "routeId": 4,
    "route": "Des Moines to Chicago",
    "eventType": "Excessive Breaking",
    "latitude": 41.62,
    "longitude": -94.58,
    "correlationId": 1,
    "geoAddress": ""
  }
]
```

**Comment by shahsank3t** [comment]
@HeartSaVioR Thanks for catching the UI issue on the different browser.

> Do we have any browser compatibility notice?

Yes. We support Chrome, Firefox, Safari and Microsoft Edge.

@sameer79 could you please fix it and verify once on different browsers? Thanks.

**Comment by sameer79** [comment]
@HeartSaVioR  Fixed the cross-browser compatibility issue and updated PR as well.

some scrolling transition need to be fixed, which will be handled in separate PR for that issue has been created the link : https://github.com/hortonworks/streamline/issues/1043

@shahsank3t I have squashed all the commit and ready for review and comment.

**Pull request closed without merging**
