### PR TITLE
ISSUE-1097 UI changes to display and search sampled events

### PR DESCRIPTION
**Pull request by sameer79**
1] Implementation of Sample in view mode for an individual component.
2] A dedicated page for Sample, shows all component events.
3] Filtering events on multiple components.
4] Search applied to keyValues, headers, auxKeyValues using "searchString"
5] Search  applied to eventId, rootIds, parentIds using "searchEventId"
6] **This PR depends on** https://github.com/hortonworks/streamline/pull/1100

@arunmahadevan @HeartSaVioR @shahsank3t, please review and test using the depend PR, open for any suggestion.
 Thanks in advanced

### CODE REVIEW

**Comment by arunmahadevan** [comment]
@sameer79 , I applied #1100 but not able to view the events.

@HeartSaVioR , I applied this PR and #1100 and built and ran streamline locally connecting to the service pool (http://ctr-e136-1513029738776-15460-01-000002.hwx.site:8080/). However the api does not seem to be returning any events in the response.

```
http://localhost:8080/api/v1/sampling/topologies/4/events?from=1513708486365&to=1513710286365&start=0&limit=25&componentName=KAFKA&componentName=RULE
```

Response: 
```
{"matchedEvents":0,"events":[]}
```

Also a few other issues,

If the topology is not deployed, I see some 404 pop ups in the view mode. We appear to be issuing requests to the sampling APIs and throwing it back in the UI. 

screen shot 2017-12-19 at 10 59 15 am


@HeartSaVioR , maybe the API should return empty results if it cant find the component from Storm (since the topology is not yet deployed). If it makes sense lets also move the API path to be within topology and be consistent with log search.

 E.g. "api/v1/catalog/topologies/:ID/component/:COMPONENTID/events"

"api/v1/catalog/topologies/:ID/events?from=1513709390245&to=1513711190245&start=0&limit=25&componentName=KAFKA"


@sameer79 The sampling setting displays percentage only up to 30. Is it intentional ? IMO, we should have all way up to 100. 

screen shot 2017-12-19 at 11 02 04 am

Also its not clear if the duration is for the sampling or log search or both. Maybe we can have some boxes or separation to clearly identify the first two are part of logging and the third one is for sampling.

**Comment by arunmahadevan** [comment]
@sameer79 , can you also rebase ?

**Comment by HeartSaVioR** [comment]
@arunmahadevan 
> I applied this PR and #1100 and built and ran streamline locally connecting to the service pool (http://ctr-e136-1513029738776-15460-01-000002.hwx.site:8080/). However the api does not seem to be returning any events in the response.

`topology.event.logger.register` should exist on topology configuration, but your topology doesn't look like having it. Your local build doesn't include https://github.com/hortonworks/streamline/pull/1095 which is not yet merged but we need to apply it manually for now.

**Comment by HeartSaVioR** [comment]
@arunmahadevan 
> If the topology is not deployed, I see some 404 pop ups in the view mode. We appear to be issuing requests to the sampling APIs and throwing it back in the UI.

https://github.com/hortonworks/streamline/blob/e1fb5b348396fbcfeaece41f7d138652d17e682d/streams/runners/storm/sampling/src/main/java/com/hortonworks/streamline/streams/sampling/service/storm/StormTopologySamplingService.java#L63-L73

We could return null if we can find topology ID in above methods. Then below method will take care of null response from samplingService.

https://github.com/hortonworks/streamline/blob/e1fb5b348396fbcfeaece41f7d138652d17e682d/streams/service/src/main/java/com/hortonworks/streamline/streams/service/TopologyEventSamplingResource.java#L174-L202

**Comment by HeartSaVioR** [comment]
@arunmahadevan 
> If it makes sense lets also move the API path to be within topology and be consistent with log search.
>
>E.g. "api/v1/catalog/topologies/:ID/events"
>
>"api/v1/catalog/topologies/:ID/events?from=1513709390245&to=1513711190245&start=0&limit=25&componentName=KAFKA"

I'll move `searchEvents` from TopologyEventSamplingResource to TopologyLoggingResource (with moving out all of log related methods from TopologyCatalogResource) and move the API path. Makes sense?

**Comment by arunmahadevan** [comment]
>I'll move searchEvents from TopologyEventSamplingResource to TopologyLoggingResource (with moving out all of log related methods from TopologyCatalogResource) and move the API path. Makes sense?

Ok fine. How about the "api/v1/sampling/topologies/:ID/component/:ID" ? IMO we can change all Urls to be under "api/v1/catalog/topologies/:ID"

**Comment by HeartSaVioR** [comment]
@arunmahadevan 
Either (current or new) is fine, but you may need to remind why you implemented APIs with path based on "/sample". We may be feeling natural for this instead of placing all the things in `/catalog/topology`.

**Comment by arunmahadevan** [comment]
@HeartSaVioR , I didn't give much thought initially. I think by keeping it under /catalog/topology everything related to topology can be in one place and it appears as is a sub resource of topology.

**Comment by sameer79** [comment]
@arunmahadevan @HeartSaVioR @shahsank3t 

> API endpoint path changes: 
 /api/v1/sampling/topologies/:topologyId(/enable|disable) /api/v1/catalog/topologies/:topologyId/sampling(/enable|disable) : DONE

pending issue: The sampling setting displays percentage only up to 30. But it should show up to 100.

**Comment by HeartSaVioR** [comment]
@sameer79 
Request on component sampling: `/` looks like missed between `sampling` and (`enable` or `disable`).

screen shot 2017-12-20 at 3 58 02 pm

I also have encountered odd case that component name got 'undefined' hence `&componentName=undefined` is added to query parameters on event query.

**Comment by sameer79** [comment]
@HeartSaVioR  Thanks for the comment, I have addressed the issues and fix on my local. After the proper testing, I'll update the PR as well. If you encounter "error" or some missing use case, do let me Know.
Thanks in advanced.

**Comment by sameer79** [comment]
@arunmahadevan @HeartSaVioR @shahsank3t 

Address the comment and updated PR as well.
squash all commit and ready for review.

**Comment by arunmahadevan** [comment]
1. In the view mode I see below request giving a 500 if topology is not deployed.

```
http://ctr-e136-1513029738776-15460-01-000002:7777/api/v1/catalog/topologies/5/logconfig
{"responseMessage":"An exception with message [Topology not found in Storm Cluster - topology id: 5] was thrown while processing request."}
```
2. The text box setting is not taking effect.
screen shot 2017-12-20 at 1 14 04 pm

Can we only have the text box with up/down for entering the sampling percentage ?

**Comment by HeartSaVioR** [comment]
@arunmahadevan 
> In the view mode I see below request giving a 500 if topology is not deployed.

Filed #1105.

**Comment by HeartSaVioR** [comment]
Submitted a patch of #1105 via #1106 (NOTE: #1106 depends on #1103)

**Comment by sameer79** [comment]
@arunmahadevan @HeartSaVioR @shahsank3t  Address the comment and updated PR as well.

**Comment by arunmahadevan** [comment]
@sameer79 , the changes look good. Raised a followup issue for fixing a few minor UI nits. (https://github.com/hortonworks/streamline/issues/1107)

@HeartSaVioR , I cannot see any events in the Sampling UI. I can see that the script is still ingesting data into kafka topics and able to read via console consumer. However the events are not seen in the events.log. The last events were around 20 mins back see below, but that is also not displayed in the search. Any idea why this event is not shown in the result?

```
2017-12-21 18:56:44.774!_DELIM_!<STREAMLINE_EVENT>!_DELIM_!SOURCE!_DELIM_!d83e5de5-cf63-4a6a-be84-7803bdc83ba8!_DELIM_![]!_DELIM_![]!_DELIM_!{driverId=22, truckId=87, eventTime=59:26.6, eventType=Normal, latitude=34.89, longitude=-91.74, eventKey=22|87|9223370572464809183, correlationId=3.66088E+18, driverName=Nadeem Asghar, routeId=1198242881, routeName= Saint Louis to Chicago Route2, eventDate=2016-05-27-22, miles=198}!_DELIM_!{}!_DELIM_!{}
```

There may be some issue with the topology itself, that the kafka spout stops ingestion after sometime.

**Comment by arunmahadevan** [comment]
It seems the component level sampling was disabled. When topology level sampling is enabled, it does not automatically turn on the component level, if component level is already disabled. Also the component level always overrides the topology level setting. So once component level sampling level is touched, it always needs to be handled at component level. 

@sameer79 , you need to display the percentage and the status of component level sampling from the response of component API. If enabled is "false", the component level setting should be shown as 0%. Right now it does not seem to consider the "enabled" flag.

@HeartSaVioR , if you think the current behavior is not intuitive, we could force the topology level setting to override the component setting whenever topology level sampling is updated.

**Comment by arunmahadevan** [comment]
@HeartSaVioR , after resetting everthing back to 100%, I am able to see events in events.log, but  still not seeing events in the UI.

Seems some issue with logfeeder seeing below exception in /var/log/ambari-logsearch-logfeeder/logfeeder.out @ ctr-e136-1513029738776-15460-01-000004.hwx.site

```
2017-12-21 20:28:46,772 [solr,hadoop_logs,worker=0] WARN  org.apache.ambari.logfeeder.output.OutputSolr$SolrWorkerThread (OutputSolr.java:393) - Solr is not reachable. Going to retry after 30 seconds. out
put=output:destination=solr,collection=hadoop_logs
org.apache.solr.common.SolrException: Could not load collection from ZK: hadoop_logs
        at org.apache.solr.common.cloud.ZkStateReader.getCollectionLive(ZkStateReader.java:986)
        at org.apache.solr.common.cloud.ZkStateReader$LazyCollectionRef.get(ZkStateReader.java:523)
        at org.apache.solr.common.cloud.ClusterState.getCollectionOrNull(ClusterState.java:189)
        at org.apache.solr.common.cloud.ClusterState.hasCollection(ClusterState.java:119)
        at org.apache.solr.client.solrj.impl.CloudSolrClient.getCollectionNames(CloudSolrClient.java:1132)
        at org.apache.solr.client.solrj.impl.CloudSolrClient.requestWithRetryOnStaleState(CloudSolrClient.java:854)
        at org.apache.solr.client.solrj.impl.CloudSolrClient.request(CloudSolrClient.java:827)
        at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:149)
        at org.apache.solr.client.solrj.SolrClient.add(SolrClient.java:106)
        at org.apache.solr.client.solrj.SolrClient.add(SolrClient.java:71)
        at org.apache.solr.client.solrj.SolrClient.add(SolrClient.java:85)
        at org.apache.ambari.logfeeder.output.OutputSolr$SolrWorkerThread.addToSolr(OutputSolr.java:462)
        at org.apache.ambari.logfeeder.output.OutputSolr$SolrWorkerThread.sendToSolr(OutputSolr.java:385)
        at org.apache.ambari.logfeeder.output.OutputSolr$SolrWorkerThread.run(OutputSolr.java:345)
Caused by: org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for /collections/hadoop_logs/state.json
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:127)
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
        at org.apache.zookeeper.ZooKeeper.getData(ZooKeeper.java:1155)
        at org.apache.solr.common.cloud.SolrZkClient$7.execute(SolrZkClient.java:345)
        at org.apache.solr.common.cloud.SolrZkClient$7.execute(SolrZkClient.java:342)
        at org.apache.solr.common.cloud.ZkCmdExecutor.retryOperation(ZkCmdExecutor.java:60)
        at org.apache.solr.common.cloud.SolrZkClient.getData(SolrZkClient.java:342)
        at org.apache.solr.common.cloud.ZkStateReader.fetchCollectionState(ZkStateReader.java:998)
        at org.apache.solr.common.cloud.ZkStateReader.getCollectionLive(ZkStateReader.java:984)
```

**Comment by HeartSaVioR** [comment]
@arunmahadevan The test cluster is small so I expect Solr instance can't live so long. I'll see I can make it back to normal.

**Comment by HeartSaVioR** [comment]
@arunmahadevan 

> It seems the component level sampling was disabled. When topology level sampling is enabled, it does not automatically turn on the component level, if component level is already disabled. Also the component level always overrides the topology level setting. So once component level sampling level is touched, it always needs to be handled at component level.
> @HeartSaVioR , if you think the current behavior is not intuitive, we could force the topology level setting to override the component setting whenever topology level sampling is updated.

Yes I feel the behavior is not intuitive, but I'm not sure fixing it because someone might be positive about current behavior. If we want to fix it, I think the fix should land to Storm with proper discussion, because the behavior is what Storm provides.

**Comment by HeartSaVioR** [comment]
I fixed an issue wrt logfeeder. We have events.log from other topology which has different time format, and multiline option in filter tries to match all of the lines in one message.
(We should note that non-Streamline topology will write the events with different time format, so that's not relevant to old/new version.)

I don't know why it doesn't happen before, but I just removed multiline option (I hope we don't have lines in event) and make it back to normal.

**Comment by arunmahadevan** [comment]
>Yes I feel the behavior is not intuitive, but I'm not sure fixing it because someone might be positive about current behavior. If we want to fix it, I think the fix should land to Storm with proper discussion, because the behavior is what Storm provides.

Ok then lets fix the UI display for now.

@sameer79 
you need to display the percentage and the status of component level sampling from the response of component API. If enabled is "false", the component level setting should be shown as 0%. Right now it does not seem to consider the "enabled" flag.

**Comment by sameer79** [comment]
@arunmahadevan address the comment regarding displaying the percentage from the component API response updated PR as well.

**Comment by shahsank3t** [comment]
@arunmahadevan @HeartSaVioR 
Merging this PR. If further changes required, we can use the follow-up issue (https://github.com/hortonworks/streamline/issues/1107)

**Pull request closed without merging**
