### PR TITLE
ISSUE-1102 Fix sampling status API to respond status 200 when topology is not running

### LINKED ISSUE #1102: Sampling status API responds HTTP 404 when topology is not running
Quoting Arun Iyer's comment in https://github.com/hortonworks/streamline/pull/1101#issuecomment-352861856:

> If the topology is not deployed, I see some 404 pop ups in the view mode. We appear to be issuing requests to the sampling APIs and throwing it back in the UI.
> maybe the API should return empty results if it cant find the component from Storm (since the topology is not yet deployed).

### PR DESCRIPTION
**Pull request by HeartSaVioR**
* Response will be changed to HTTP status 200 with success = "false" when topology is not running
* Also refactor a bit based on suggestion (moving methods, API endpoint paths)

> API endpoint path change:

* /api/v1/sampling/topologies/:topologyId(/enable|disable) -> /api/v1/catalog/topologies/:topologyId/sampling(/enable|disable)
* /api/v1/sampling/topologies/:topologyId/component/:componentId(/enable|disable) -> /api/v1/catalog/topologies/:topologyId/component/:componentId/sampling(/enable|disable)
* /api/v1/sampling/topologies/:topologyId/events -> /api/v1/catalog/topologies/:topologyId/events

This closes #1102

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
@arunmahadevan @shahsank3t @sameer79 
Please take a look. Given that this patch modifies the API endpoint paths which are related to #1101, this patch is effectively blocker for #1101.

@sameer79 I think this patch should be applied to #1101. Please take a look at the API endpoint paths.

**Comment by arunmahadevan** [comment]
@HeartSaVioR , the component sampling status returns the topology sampling status. I seem to have used the same client API at [both places](https://github.com/hortonworks/streamline/blob/master/streams/runners/storm/sampling/src/main/java/com/hortonworks/streamline/streams/sampling/service/storm/StormTopologySamplingService.java#L64-L73). Can you fix it?

**Comment by HeartSaVioR** [comment]
@arunmahadevan Fixed and now building. I'll update the PR once build succeeds.

**Comment by HeartSaVioR** [comment]
@arunmahadevan Addressed.

**Comment by arunmahadevan** [comment]
+1

**Pull request closed without merging**
