### PR TITLE
ISSUE-1288 SAM aggregate processor doesn't show the aggregation function

### PR DESCRIPTION
**Pull request by sameer79**

### CODE REVIEW

**Comment by sameer79** [comment]
Aggregate Processor screenshot below:-

aggregate-screenshot

**Comment by arunmahadevan** [comment]
@sameer79 , the changes are good. However we need to make sure that user passes only aggregate expressions (the truckId in the screenshot that you have uploaded is invalid). Right now it would fail at runtime so I have added some backend validations https://github.com/hortonworks/streamline/pull/1290

If possible can you also disable such expressions from the UI ?

**Comment by sameer79** [comment]
The users will be forced to select a function before choosing the field and if a user just passes only a field the validation has been added to handle that case too.
Help has been added to bring up the pop up (like pressing @ in other processors)

@arunmahadevan  can you please verify the same, thanks in advanced

**Comment by arunmahadevan** [comment]
+1

**Pull request closed without merging**
