### PR TITLE
ISSUE-1015 Quote `window` when defining tables to avoid reserved word conflicts

### PR DESCRIPTION
**Pull request by navbruce**
Leaving `window` unquoted causes table creation to fail when using MariaDB v10.2

### CODE REVIEW

**Comment by arunmahadevan** [comment]
+1. @navbruce , thanks for the patch. can you create a github issue and update the PR title to include the ISSUE ?

**Comment by HeartSaVioR** [comment]
@navbruce @arunmahadevan 
Wouldn't it better to escape all the field name for MySQL as we do for Oracle and PostgreSQL?

**Comment by navbruce** [comment]
@HeartSaVioR Probably yes? I just followed the existing pattern in that MySQL create_tables file.

**Comment by arunmahadevan** [comment]
@HeartSaVioR  yes we could escape all. @navbruce, do you want to take it up as part of this PR ?

**Comment by navbruce** [comment]
I looked at the PostgreSQL and Oracle create table statements and tried to match what they're doing as best I could.

MySQL doesn't support double quotes for field identifiers, only back-tick quoting. Other than that, I quoted all field and index names.

**Comment by arunmahadevan** [comment]
@navbruce , the changes looks good. We require non Hortonworks contributors to sign an iCLA document before accepting contributions. If thats the case can you let me know your email-id where I can send the doc?

**Comment by arunmahadevan** [comment]
@navbruce , waiting for you to return the ICLA to merge this in.

**Comment by navbruce** [comment]
Hi Arun,

I’m really sorry, my boss wasn’t available yesterday and I need his approval to sign the agreement. We should be meeting this morning and I’ll take it up then for sure.

Thanks,
- Bruce

**Comment by arunmahadevan** [comment]
@navbruce , ping. Can you also rebase with latest master ?

**Comment by navbruce** [comment]
I hope that worked. There were a lot of changes to that file so I attempted to add my changes as conservatively as possible.

Also, waiting to get the go-ahead from the company lawyer on the contributor agreement. Management is very supportive, but none of this is as quick as could be hoped for.

**Comment by HeartSaVioR** [comment]
@navbruce Hello. Do you have any update here? Just a friendly reminder.

**Comment by HeartSaVioR** [comment]
Already addressed.

**Pull request closed without merging**
