### PR TITLE
BUG-81257 Refactor JSON Output Schema For KafkaBundleHintProvider and KafkaSinkBundleHintProvider

### PR DESCRIPTION
**Pull request by hmcl**

### CODE REVIEW

**Comment by hmcl** [comment]
@harshach @priyank5485 this PR sits on top of https://github.com/hortonworks/streamline/pull/587, which itself sits on top of https://github.com/hortonworks/streamline/pull/577. PR https://github.com/hortonworks/streamline/pull/577 should be merged first, then PR https://github.com/hortonworks/streamline/pull/587 and then this. I can take care of this once we have +1.

**Comment by harshach** [comment]
@hmcl I merged in the order you specified but still running into merge issues

**Comment by harshach** [comment]
@hmcl can you resolve this conflicts quickly

**Comment by harshach** [comment]
or just open 1 PR that can be merged into the master

**Comment by hmcl** [comment]
@harshach working on it

**Comment by hmcl** [comment]
@harshach DONE!

**Comment by harshach** [comment]
@hmcl This patch is not getting merged in after merging in https://github.com/hortonworks/streamline/pull/577 https://github.com/hortonworks/streamline/pull/587
hence the reason I asked you to open 1 PR to get it in

**Pull request merged**
