### PR TITLE
ISSUE-1107: UI issues in view mode

### PR DESCRIPTION
**Pull request by shahsank3t**
This PR contains changes from @sameer79's PR (https://github.com/hortonworks/streamline/pull/1111) and addressed following comments by @arunmahadevan https://github.com/hortonworks/streamline/pull/1111#issuecomment-353690604

> 1. In the Sampling screen selected "Event Id" and "Root Id". Able the view the values. However after I go back to view mode and come back to the sampling view, these settings are not saved. Same behavior while selecting "host" in the log search. Can we save these settings?
> 2. Add a sort option in the UI to view the result in ascending or descending order.

### CODE REVIEW

**Comment by shahsank3t** [comment]
@arunmahadevan 
We are now saving the state of column filters (except for Date/Time, Component Name and Key values column -- even if a user hides, it will still be visible on coming back to the page) and also saving the state of sorting.

Just to keep in mind, we are using browser's `LocalStorage` to save the state of column filter/sorting, so the state will be maintained till the data is present else fallback to default setting (which user sees when he loads the page for the first time)

**Comment by arunmahadevan** [comment]
@shahsank3t , thanks for addressing the changes. Can you make similar changes in the log search UI as well (for host and port) ?

**Comment by shahsank3t** [comment]
@arunmahadevan Addressed your comment to add the similar change to log search page.

**Comment by arunmahadevan** [comment]
Thanks @shahsank3t , @sameer79 , merged the commits to master.

**Pull request closed without merging**
