### PR TITLE
STREAMLINE-775: Add builtin field for udfs & notifiers that are being added by bootstrap

### PR DESCRIPTION
**Pull request by omkreddy**

### CODE REVIEW

**Comment by omkreddy** [comment]
@shahsank3t added a field "builtin" to "UDF" and "Notifier" objects.  Currently, we are just storing the value. Let me know if we need to add specific server side logic

**Comment by shahsank3t** [comment]
@omkreddy Thanks, this is good. We don't need any server-side specific logic change :)

**Comment by shahsank3t** [comment]
@omkreddy - On running bootstrap.sh, I am getting error for all the UDF's and Notifiers saying:
{"responseMessage":"An exception with message [java.lang.Boolean cannot be cast to java.lang.String] was thrown while processing request."}

**Comment by omkreddy** [comment]
@shahsank3t I already fixed it on friday. You may be using initial commit. pl take latest PR

**Comment by shahsank3t** [comment]
@omkreddy Took the latest PR today and verified. Still the same issue. Can you please verify again?

**Comment by omkreddy** [comment]
@shahsank3t oops..sorry..forgot to push my change.. pl take latest PR

**Comment by shahsank3t** [comment]
+1

**Comment by shahsank3t** [comment]
@omkreddy, I am not able to post with "builtin" as false. Can you please make the required changes for that.

Getting error as: "An exception with message [com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'builtin' at row 1] was thrown while processing request."

**Comment by omkreddy** [comment]
@shahsank3t  increased the column width. Pl try latest

**Comment by omkreddy** [comment]
@shahsank3t let me know if any changes required. thanks

**Comment by shahsank3t** [comment]
@omkreddy no, nothing more required. Good to merge in.

**Pull request merged**
