### PR TITLE
ISSUE-1310 Unable to save projection when using select all Projection Fields

### PR DESCRIPTION
**Pull request by sameer79**
@arunmahadevan @shahsank3t  ready for review comment.

### CODE REVIEW

**Comment by arunmahadevan** [comment]
@sameer79 
Even with the fix, I am not able to save unless I select something in the "Projection Expression". This should not be mandatory and one should be able to save just by selecting one or more "Projection fields". Can you check?

**Comment by arunmahadevan** [comment]
Actually both "Projection Expression" and "Projection Fields" should not be mandatory. We should be able to save as long as there is at-least one value in either "Projection Expression" or "Projection Fields".

**Comment by shahsank3t** [comment]
@sameer79 - I believe you replaced `let` & `const` at some places with `var` keyword. Any specific reason not to change it everywhere?

**Comment by shahsank3t** [comment]
@arunmahadevan - Changes you mentioned in the comment above are kind of UI enhancement which needs to be implemented. 
My suggestion is to create another Github issue for that enhancement and track from there and just verify the current issue here.

**Comment by sameer79** [comment]
@shahsank3t address the comment and updated the PR as well.

**Comment by arunmahadevan** [comment]
+1

@sameer79 @shahsank3t able to save projections with a subset of or "select all" fields in chrome and Firefox. We can address the issue of making the "Projection Expression" optional in a separate issue.

**Comment by arunmahadevan** [comment]
Raised https://github.com/hortonworks/streamline/issues/1314 for followup.

**Pull request closed without merging**
